# Configuration file for NLP project
project:
  name: nlp-absa-project
  description: Aspect-Based Sentiment Analysis (ABSA) for Vietnamese reviews car from youtube
  language: vi
  seed: 42

# File
paths:
  data_root: data
  raw: data/raw
  processed: data/processed
  external: data/external
  models: models
  models_ml: models/ml # Save artifacts of ML models
  models_dl: models/dl # Save artifacts of DL models
  logs: logs

# Data settings
dataset:
  task: absa
  train_file: data/processed/train.csv
  val_file: data/processed/val.csv
  test_file: data/processed/test.csv
  # Column names in your processed CSV files
  text_column: text
  aspect_column: aspect
  polarity_column: polarity

  # Label spaces
  aspects:
    - key: brand
      description: Nhận diện thương hiệu
    - key: exterior
      description: Thiết kế bên ngoài (ngoại thất), Kiểu dáng, Các chi tiết bên ngoài
    - key: interior
      description: Nội thất của xe, Không gian bên trong
    - key: performance
      description: Vận hành (Động cơ, chạy êm, hộp số, vô lăng, phanh, chân ga, ...)
    - key: features
      description: Tính năng, trang bị, công nghệ
    - key: cost
      description: Chi phí (giá bán, chi phí, tiết kiệm nhiên liệu, đáng tiền, sửa chữa, ...)

  polarities: [positive, negative, neutral]

  # Optional: numeric ids for stable mapping in models/scripts
  mappings:
    polarity_to_id:
      negative: 0
      neutral: 1
      positive: 2
    aspect_to_id:
      brand: 0
      exterior: 1
      interior: 2
      performance: 3
      features: 4
      cost: 5

# Experiment selector
experiment:
  model_family: svm # Select model: svm | logistic | xgboost | UNGTHU
  search_method: grid # grid | random | optuna

# Model-specific configs
ml_configs:
  svm: config/ml/svm.yaml
  logistic: config/ml/logistic.yaml
  xgboost: config/ml/xgboost.yaml
  UNGTHU: config/dl/UNGTHU.yaml

# Save logs and checkpoints
logging:
  tensorboard_dir: logs/tensorboard
  training_log: logs/training.log
  hpo_dir: logs/hpo # (Optionally) Directory for HPO results
  hpo_ml_dir: logs/hpo/ml # (Optionally) Separate HPO results for ML
  hpo_dl_dir: logs/hpo/dl # (Optionally) Separate HPO results for DL

# Runtime settings
runtime:
  use_gpu: false
  batch_size: 32
  num_workers: 4
