# SVM Model Configuration
model: svm
type: ml

# GridSearchCV
grid_search:
  # Cross-Validation settings
  cv: 5

  # Scoring metric
  scoring: f1_macro
  n_jobs: -1

  # Hyperparameter grid
  param_grid:
    C: [1., 2., 3., 4., 5., 6., 7., 8., 9., 10.]
    kernel: ["linear", "rbf", "poly", "sigmoid"]
    gamma: ["scale", "auto"]
