# SVM Model Configuration
model: svm
type: ml

# GridSearchCV
grid_search:
  # Cross-Validation settings
  cv: 5

  # Scoring metric
  scoring: f1_micro
  n_jobs: -1

  # Hyperparameter grid
  param_grid:
    C:
      [
        0.1,
        0.61025641,
        1.12051282,
        1.63076923,
        2.14102564,
        2.65128205,
        3.16153846,
        3.67179487,
        4.18205128,
        4.69230769,
        5.2025641,
        5.71282051,
        6.22307692,
        6.73333333,
        7.24358974,
        7.75384615,
        8.26410256,
        8.77435897,
        9.28461538,
        9.79487179,
        10.30512821,
        10.81538462,
        11.32564103,
        11.83589744,
        12.34615385,
        12.85641026,
        13.36666667,
        13.87692308,
        14.38717949,
        14.8974359,
        15.40769231,
        15.91794872,
        16.42820513,
        16.93846154,
        17.44871795,
        17.95897436,
        18.46923077,
        18.97948718,
        19.48974359,
        20.,
      ]
    kernel: ["linear", "rbf", "poly", "sigmoid"]
    gamma: ["scale", "auto"]
