# SVM Model Configuration
model: svm
type: ml

# GridSearchCV
grid_search:
  # Cross-Validation settings
  cv: 5

  # Scoring metric
  scoring: f1_micro
  n_jobs: -1

  # Hyperparameter grid
  param_grid:
    C: [0.1, 1.0, 10.0, 100.0]
    kernel: ["linear", "rbf", "poly", "sigmoid"]
    gamma: ["scale", "auto"]
